name: kuzzle
version: 3.0.6
description: A library to interact with kuzzle API. A backend software,
  self-hostable and ready to use to power modern cross-platform apps.
homepage: https://github.com/kuzzleio/sdk-dart
environment:
  sdk: ">=2.12.0 <4.0.0"
dependencies:
  pedantic: ^1.11.1
  meta: ^1.4.0
  uuid: ^4.3.3
  http: ^1.2.1
  mockito: ^5.0.10
dev_dependencies:
  test: ^1.17.8
  coverage: ^1.0.3
