name: Generate DartDoc
description: Dart Documentation Generation
runs:
  using: "composite"
  steps: 
    - name: Run DartDoc
      run: |
        ./docker_launch.sh
        dartdoc
      shell: bash
